model:
  init_name: large-v2
  bfloat16: False # If this is set, mixed_precision_training will use bfloat16
  lora: False
dataset:
  train_datasets: [i4ds/sds-spc-stt4sg-sentence-level-train-val]
  select_n_per_t_ds: [null]
  val_datasets: [i4ds/sds-spc-stt4sg-sentence-level-train-val]
  select_n_per_v_ds: [1000]
  train_split_name: "train"
  valid_split_name: "validation"
  no_timestamp_training: True
  max_prompt_length: 223
  prompt_use_rate: 0.0
  no_timestamp_rate: 0.5
  batch_size: 16
  batch_size_eval: 16
lr_scheduler:
  type: linear
  warmup_steps: 128
optimizer:
  type: adamw
  8bit: True
  params:
    lr: 2.0e-4
    weight_decay: 0.1
    betas: (0.9, 0.98)
    eps: 1.0e-6
    amsgrad: False
training:
  accum_grad_steps: 16
  train_only_decoder: False
  train_only_encoder: False
  max_grad_norm: 1.0
  epochs: 2
  eval_steps: 50
  eval_warmup: 0
  eval_steps_early: 50
  save_all_checkpoints: False
  mixed_precision_training: True
  mp_dtype: fp16
  gradient_checkpointing_encoder: True
  gradient_checkpointing_encoder_last_only: False
  gradient_checkpointing_decoder: True
augmentation:
  spec_augment:
    apply: True
    time_mask_param: 100
    p: 1.0
    freq_mask_param: 27
    time_warp_w: 80
 audio_augment:
    apply: True
    lpf: # Low pass filter
      min_cutoff_freq: 1500
      max_cutoff_freq: 1907
    hpf: # High pass filter
      min_cutoff_freq: 211
      max_cutoff_freq: 400
    acn:  # Colored noise
      min_snr_in_db: 10
seed: 123
save_dir: output