model:
  init_name: small
  fp16: True
dataset:
  train_datasets: [i4ds/stt4sg-350_train_all_fold_0, i4ds/stt4sg-350_train_all_fold_1]
  val_datasets: [i4ds/stt4sg-350_valid_fold_0]
  no_timestamp_training: False
  prompt_use_rate: 0.5
  no_timestamp_rate: 0.5
  batch_size: 4
lr_scheduler:
  type: cosine_with_warmup_restarts_chill
  num_cycles: 3
  lr_gamma: 0.5
  chill_steps: 100
  chill_range: 0.02
optimizer:
  type: adamw
  8bit: True
  params:
    lr: 0.0001
    weight_decay: 0.1
    betas: [0.9, 0.98]
    eps: 1e-9
    amsgrad: False
training:
  accum_grad_steps: 32
  warmup_steps: 500
  max_grad_norm: 1.0
  train_steps: 5000
  eval_steps: 500
  save_all_checkpoints: False
  seed: 123
  batch_size: 1
  batch_size_eval: 16
augmentation:
  spec_augment:
    apply: True
    time_mask_param: 100
    p: 1.0
    freq_mask_param: 27
seed: 42
save_dir: ./output