model:
  init_name: tiny
  bfloat16: False # If this is set, mixed_precision will use bfloat16
dataset:
  train_datasets: [i4ds/SDS_STT_SPC_mixed]
  val_datasets: [i4ds/SDS_STT_SPC_mixed]
  train_split_name: "train"
  valid_split_name: "validation"
  no_timestamp_training: False
  max_prompt_length: 223
  prompt_use_rate: 0.5
  no_timestamp_rate: 0.5
  batch_size: 16
  batch_size_eval: 16
lr_scheduler:
  type: linear
  num_cycles: 3
  warmup_steps: 500
optimizer:
  type: adamw
  8bit: True
  params:
    lr: 0.0001
    weight_decay: 0.1
    betas: (0.9, 0.98)
    eps: 1.0e-9
    amsgrad: False
training:
  accum_grad_steps: 1
  train_only_decoder: False
  max_grad_norm: 1.0
  train_steps: 100
  eval_steps: 200
  eval_warmup: 0
  eval_steps_early: 500
  save_all_checkpoints: False
  mixed_precision: True
  mp_dtype: fp16
  gradient_checkpointing: False
augmentation:
  spec_augment:
    apply: True
    time_mask_param: 100
    p: 1.0
    freq_mask_param: 27
seed: 123
save_dir: ./output